---
title: "TWIST-EFS DSMB"
date: "2025-TBD"
format:
  docx:
    toc: true
    reference-doc: template.docx
  pdf:
    toc: true
  html:
    number-sections: true
    theme: cerulean
    highlight: kate
    toc: true
    toc-float:
      collapsed: false
      smooth-scroll: true
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
 knitr::opts_chunk$set(echo = TRUE) 
library(knitr)
library(dplyr)
library(tibble)
library(flextable)
library(tinytex)
library(officer)
library(stringr)
library(lubridate)
library(ggplot2)
library(lubridate)
library(stringr)
library(showtext)
library(patchwork)
load("C:/Users/luke_hall/OneDrive - Edwards Lifesciences/lhall/TWIST_EFS/data_archive/data_2025JUL16.RData")
source("C:/Users/luke_hall/OneDrive - Edwards Lifesciences/lhall/TWIST_EFS_2025_11_DSMB/programs/makedata/mk_adsl.R")
source("C:/Users/luke_hall/OneDrive - Edwards Lifesciences/lhall/TWIST_EFS_2025_11_DSMB/programs/makedata/mk_adsv.R")
source("C:/Users/luke_hall/OneDrive - Edwards Lifesciences/lhall/TWIST_EFS_2025_11_DSMB/programs/makedata/mk_adststat.R")
```


# Tables


## Table 1 Enrollment by Site
```{r table1}
#| echo: false
#source("C:/Users/luke_hall/OneDrive - Edwards Lifesciences/lhall/TWIST_EFS_2025_11_DSMB/programs/makedata/mk_adsl.R")
source("C:/Users/luke_hall/OneDrive - Edwards Lifesciences/lhall/TWIST_EFS_2025_11_DSMB/programs/TLFs/t1_enrollmentbysite.R")

t1_enrollmentbysite <- flextable(t1) %>%
  set_caption(caption = NULL) %>%
  set_header_labels(
    SiteNumber = "Site Number",
    SiteName = "Site Name",
    print_enrolled = paste0("Enrolled\u00B9 (N=", totaln_enrolled, ")"),
    print_implanted = paste0("Implanted\u00B2 (N=", totaln_implanted, ")")
  ) %>%
  autofit() %>%
  font(fontname = "Calibri", part = "all") %>%
  fontsize(size = 11, part = "all") %>%
  align(align = "left", part = "all") %>%
  bold(i = 1, part = "header") %>%
  bg(i = 1, bg = "#D3D3D3", part = "header") %>%
  border(part = "all", border = officer::fp_border(color = "grey70", width = 1)) %>%
  width(j = 1, width = 1.25) %>%    
  width(j = 2, width = 2.75) %>% 
  width(j = 3:4, width = 2) %>%
  add_footer_lines(c(
    "[1] Enrolled: A patient is considered enrolled if they have signed informed consent and have the study procedure attempted (defined as introduction of the investigational delivery system into the patient).",
    "[2] Implanted: A patient is considered implanted if they have undergone the study procedure and leave the operating room with the study valve in place.",
    "Categorical measures: %",
    program_info
  )) %>%
  font(fontname = "Calibri", part = "footer") %>%
  fontsize(size = 11, part = "footer") %>%
  border_outer(part = "footer") %>%
  fix_border_issues()


t1_enrollmentbysite
```


## Table 2 Patient Disposition & Follow-up Visit Compliance by Interval
```{r table2}
#| echo: false
source("C:/Users/luke_hall/OneDrive - Edwards Lifesciences/lhall/TWIST_EFS_2025_11_DSMB/programs/TLFs/t2_patientdisposition.R")

t2_patientdisposition <- flextable(visit_df) %>%
  set_caption(caption = NULL) %>%
  autofit() %>%
  font(fontname = "Calibri", part = "all") %>%
  fontsize(size = 11, part = "all") %>%
  align(align = "left", part = "all") %>%
  bold(i = 1, part = "header") %>%
  bg(i = 1, bg = "#D3D3D3", part = "header") %>%
  padding(i = 2:4, j = 1:5, padding.left = 40) %>%
  border(part = "all", border = officer::fp_border(color = "grey70", width = 1)) %>%
  width(j = 1, width = 2.25) %>%
  width(j = 2:5, width = 1.75) %>%
  add_footer_lines(c(
    "[1] Patients are eligible if they complete the visit or their visit window is open and prior to FU visit window , they (a) are alive , (b) are not explanted,  (c) did not withdraw from study,  (d) are not lost to FU.",
    "[2] Specify the visit window: 30 Days FU window (23-37 days), 6 FU window (166-194 days), 1 year FU window (335-390 days).",
    "Categorical measures: %",
    program_info
  )) %>%
  font(fontname = "Calibri", part = "footer") %>%
  fontsize(size = 11, part = "footer") %>%
  border_outer(part = "footer") %>%
  fix_border_issues()

t2_patientdisposition
```


## Table 3 Demographics and Baseline Characteristics
```{r table3, message=FALSE, warning=FALSE}
#| echo: false
source("C:/Users/luke_hall/OneDrive - Edwards Lifesciences/lhall/TWIST_EFS_2025_11_DSMB/programs/TLFs/t3_baselinedem.R")
t_baseline <- flextable(summary_table) %>%
  set_header_labels(
    Variable = "Baseline Characteristic",
    Statistic = "Total"
  ) %>%
  width(j = 1, width = 3) %>%
  width(j = 2, width = 3) %>%
  font(fontname = "Calibri", part = "all") %>%
  fontsize(size = 11, part = "all") %>%
  align(align = "left", part = "all") %>%
  bold(i = 1, part = "header") %>%
  bg(i = 1, bg = "#D3D3D3", part = "header") %>%
  border(part = "all", border = officer::fp_border(color = "grey70", width = 1)) %>%
  add_footer_lines(c(
    "Continuous variables: Mean ± SD (n); Median (min, max)",
    "Categorical measures: n/Total N (%)",
    program_info
  )) %>%
  font(fontname = "Calibri", part = "footer") %>%
  fontsize(size = 11, part = "footer") %>%
  border_outer(part = "footer") %>%
  fix_border_issues()

t_baseline
```


## Table 11 CEC Adjudicated Heart Failure Hospitalizations and Non-elective Mitral Valve Reinterventions
```{r table11}
#| echo: false
#source("C:/Users/luke_hall/OneDrive - Edwards Lifesciences/lhall/TWIST_EFS_2025_11_DSMB/programs/makedata/mk_adsl.R")
source("C:/Users/luke_hall/OneDrive - Edwards Lifesciences/lhall/TWIST_EFS_2025_11_DSMB/programs/TLFs/t11_CEC_HFH_MVR.R")

tab <- 
  flextable(allresults) %>%
  set_caption(caption = NULL) %>%
  set_header_labels(
    Category = "",
    E_NEvents="No. Events", 
    E_Patients="Patients",
    L_NEvents="No. Events", 
    L_Patients="Patients",
    T_NEvents="No. Events", 
    T_Patients="Patients"
  ) %>%
  add_header_row(
    top = TRUE,
    values = c("Category", "Early Events \n (\u2264 30 Days)", 
               "Late Events \n (\u003E 30 Days to 1 Year)", "Total Events"),
    colwidths = c(1, 2, 2, 2) # Example: 1 column for "Main Header", 1 for "Sub Header 1", 1 for "Sub Header 2"
  ) %>%
  autofit() %>%
  font(fontname = "Calibri", part = "all") %>%
  fontsize(size = 11, part = "all") %>%
  align(align = "center", part = "body") %>%
  align(i=1:2, j=1, align = "left", part = "body") %>%
  align(i=1:2, align = "center", part = "header") %>%
  bold(i = 1:2, part = "header") %>%
  bg(i = 1:2, bg = "#D3D3D3", part = "header") %>%
  border(part = "all", border = officer::fp_border(color = "grey70", width = 1)) %>%
  width(j = 1, width = 2) %>%    
  width(j = 2:7, width = 1) %>% 
  #width(j = 3:4, width = 2) %>%
  add_footer_lines(c(
    "Categorical measures (%)",
    program_info
  )) %>%
  font(fontname = "Calibri", part = "footer") %>%
  fontsize(size = 11, part = "footer") %>%
  border_outer(part = "footer") %>%
  fix_border_issues()

merge_at(tab, i = 1:2, j = 1, part = "header")

tab
```


# Figures


## Figure 1 Linear Graph of Cumulative Enrollment by Month
```{r figure1}
#| echo: false
source("C:/Users/luke_hall/OneDrive - Edwards Lifesciences/lhall/TWIST_EFS_2025_11_DSMB/programs/TLFs/f1_accrualbymonth.R")

f1_accrualbymonth <- ggplot(data = accrual, aes(x = new_date)) +
  geom_line(aes(y = csum)) +
  geom_point(aes(y = csum)) +
  geom_text(aes(y = csum, label = csum), hjust = 0.5, vjust = -2, size = 3, color = "black") +
  scale_x_date(date_breaks = "2 months", date_labels = "%b %Y", expand = c(0.01, 0)) +
  scale_y_continuous(expand = c(0.01, 0), limits = c(0, 40), breaks = seq(0, 40, 5)) +
  ylab("Number of Patients Enrolled") +
  xlab("") +
  ggtitle(paste0("Enrolled Population (N=", totaln_enrolled, ")")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


# Load system fonts and activate
font_add("calibri", regular = "C:/Windows/Fonts/calibri.ttf")
showtext_auto()

footer <- ggplot() +
  geom_text(aes(x = 0, y = 0, label = program_info), hjust = 0, size = 3.5, family = "calibri") +
  xlim(0, 1) +  # stretch x range so text aligns far left
  theme_void() +
  theme(plot.margin = margin(t = -10, r = 0, b = 5, l = 5, unit = "pt"))

# Combine plot and footnote
final_plot <- f1_accrualbymonth / footer + plot_layout(heights = c(6, 1))

final_plot
```
